### ISSUE TITLE
stream errors are not handled correctly on streams other than the first

### ISSUE THREAD

**Issue by catdad** [feross/multistream#17]
When multiple streams are passed in directly, and a stream other than the first one immediately has an error (file read permission, perhaps), that errors throws instead of being handled. Here's an example:

```javascript
multistream([
  fs.createReadStream('file/that/works/fine'),
  fs.createReadStream('file/with/no/read/permission')
]);
```

This will throw the read permission error. I can change the code to this to make it work:

```javascript
multistream([
  fs.createReadStream('file/that/works/fine'),
  function() { return fs.createReadStream('file/with/no/read/permission'); }
]);
```

However, it feels like I shouldn't have to do that. Not a big deal, since it's better not to open all of the files at the same time anyway, but still, the docs suggest that it should work just fine and it probably needs to.

**Comment by feross** [comment]
I think you're right. Here's a PR to fix this issue: https://github.com/feross/multistream/pull/18
