### ISSUE TITLE
TypeScript types

### ISSUE THREAD

**Issue by tikotzky** [feross/multistream#20]
Hi,

I'm using this project from within TypeScript and created types for it.
Would you be interested in a PR which put the types into the repo?
All it would require is a single `index.d.ts` in the root of the module containing the types below.
You can see how redux does it [here](https://github.com/reactjs/redux/blob/master/index.d.ts)

Thanks

```ts
import { Readable, ReadableOptions } from 'stream';

type StreamGenerator = () => Readable;
type AsyncStreamFactory = (callback: AsyncResultCallback<Readable, Error>) => void;
type Streams = (Readable | StreamGenerator)[] | AsyncStreamFactory;

interface MultiStream {
  new (streams: Streams, opts?: ReadableOptions): Readable;
  (streams: Streams, opts?: ReadableOptions): Readable;
  obj(streams: Streams): Readable;
}
declare const _MultiStream: MultiStream;
export = _MultiStream;

```

**Comment by tikotzky** [comment]
I left one part out...
It should also include a `typings` property in `package.json`

again see redux [here](https://github.com/reactjs/redux/blob/dbb9f070970d4b41703aff304d73ee67767ac9ff/package.json#L9)

**Comment by feross** [comment]
Sorry, I don't use Typescript so this file will get out of date as the API changes.
