### ISSUE TITLE
file without "new line" at the end

### ISSUE THREAD

**Issue by sergueyarellano** [feross/multistream#25]
Hi!

When I use multistream for `file 1` and `file 2` and consume the stream line by line I see this:

```
aaa
bbb
cccxxx
yyy
zzz
```

file 1
```
aaa
bbb
ccc
```

file2
```
xxx
yyy
zzz

```

Is this the correct behaviour?

I would prefer that a `new line` is added at the end of the files that don't have it. :)

**Comment by mafintosh** [comment]
multistream just combines two streams, however they may look. it doesn't do any sort of mapping of the content etc. you might wanna parse it through a transform stream first to make it behave the way you want :)

**Comment by sergueyarellano** [comment]
hehe, boom!
