### ISSUE TITLE
Work with Video MP4?

### ISSUE THREAD

**Issue by fabioharry** [feross/multistream#36]
I wonder if it works with streaming video is MP4?

Thanks!

**Comment by mykeels** [comment]
It doesn't seem to @fabioharry ... The resultant stream is the size of the combined mp4 streams, but only the first video plays when I try to.

MP4 isn't directly concatenate-able, apparently.

You'd have to concatenate the MP4 videos with a tool like ffmpeg, using a command like: 

```sh
ffmpeg -i /path/to/video0.mp4 -i /path/to/video1.mp4 -i /path/to/video2.mp4 -filter_complex "[0:v] [0:a] [1:v] [1:a] [2:v] [2:a] concat=n=3:v=1:a=1 [v] [a]" -map "[v]" -map "[a]" /path/to/output.mp4
```

See this [blog post](https://www.bugcodemaster.com/article/concatenate-videos-using-ffmpeg).
