### ISSUE TITLE
Feature request: append

### ISSUE THREAD

**Issue by fkautz** [feross/multistream#8]
CombinedStream has the following:

```js
var combinedStream = CombinedStream.create();
combinedStream.append(function(next) {
  next(fs.createReadStream('file1.txt'));
});
combinedStream.append(function(next) {
  next(fs.createReadStream('file2.txt'));
});
```

It would be useful to support append in multistream as well.

**Comment by feross** [comment]
What are you trying to accomplish? You can already pass in a function to lazily create a stream (see the readme).

**Comment by fkautz** [comment]
Infinite lazy streams. :)

**Comment by feross** [comment]
PR welcome!

**Comment by feross** [comment]
PR still welcome, but closing this stale issue.
